### ISSUE TITLE
Show point card on tap

### ISSUE THREAD

**Issue by lerastromtsova** [dh-center/st-retrospect-mobile#8]
When viewing points on a map, a user should be able to tap on any point and see the point card.
Also, there should be a possibility to hide the card and return to original state.
### Subtasks:
- [x] Design point card

- [x] Implement point card on tap

- [x] Implement returning back to the map
